Description:
  This template deploys a VPC, with a pair of public and private subnets spread
  across two Availability Zones. It deploys an internet gateway, with a default
  route on the public subnets. It deploys a NAT gateway for the first private subnet,
  and default routes for it.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
  VpcId:
    Description: The VPC where the EC2 Instance will be launched
    Type: String
  SubnetId:
    Description: The Subnet where the EC2 Instance will be launched
    Type: String
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH Key to use
  ImageId:
    Description: An AMI ID for the EC2 Instance
    Type: String
    Default: ami-0c94855ba95c71c99
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - m4.large
      - m4.xlarge
      - c4.large
      - c4.xlarge
  SecurityGroup:
    Type: String
    Description: Security group for the EC2 Instance
  DBAddress:
    Type: String
    Description: Database endpoint
  DBName:
    Type: String
    Description: Database name
  DBUsername:
    Type: String
    Description: Username for MySQL database access
  DBPassword:
    Type: String
    Description: Password MySQL database access

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      'AWS::CloudFormation::Init':
        config:
          files:
            /wp-config.php:
              content: !Join 
                - ''
                - - |
                    <?php
                  - 'define(''DB_NAME'',          '''
                  - !Ref DBName
                  - |
                    ');
                  - 'define(''DB_USER'',          '''
                  - !Ref DBUsername
                  - |
                    ');
                  - 'define(''DB_PASSWORD'',      '''
                  - !Ref DBPassword
                  - |
                    ');
                  - 'define(''DB_HOST'',          '''
                  - !Ref DBAddress
                  - |
                    ');
                  - |
                    define('DB_CHARSET',       'utf8');
                  - |
                    define('DB_COLLATE',       '');
                  - |
                    $table_prefix = 'wp_';
                  - |
                    require_once( ABSPATH . 'wp-settings.php' );
              mode: '000644'
              owner: root
              group: root
    Properties:
      KeyName: !Ref KeyName
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
      - AssociatePublicIpAddress: True
        DeleteOnTermination: True
        DeviceIndex: 0
        GroupSet: 
          - !Ref SecurityGroup
        SubnetId: !Ref SubnetId
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install httpd php php-mysql -y
          cd /var/www/html
          wget https://wordpress.org/wordpress-5.1.1.tar.gz
          tar -xzf wordpress-5.1.1.tar.gz
          cp -r wordpress/* /var/www/html/
          cp -r wp-config.php /var/www/html/wordpress/wp-config.php
          rm -rf wordpress
          rm -rf wordpress-5.1.1.tar.gz
          chmod -R 755 wp-content
          chown -R apache:apache wp-content
          wget https://s3.amazonaws.com/bucketforwordpresslab-donotdelete/htaccess.txt
          mv htaccess.txt .htaccess
          chkconfig httpd on
          service httpd start
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ec2

Outputs:
  Ec2Id:
    Value: !Ref EC2Instance

  Ec2PublicId:
    Value: !GetAtt EC2Instance.PublicIp
