Description:
  This template deploys a VPC, with a pair of public and private subnets spread
  across two Availability Zones. It deploys an internet gateway, with a default
  route on the public subnets. It deploys a NAT gateway for the first private subnet,
  and default routes for it.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
  VpcId:
    Description: The VPC where the EC2 Instance will be launched
    Type: String
  SubnetId:
    Description: The Subnet where the EC2 Instance will be launched
    Type: String
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH Key to use
  ImageId:
    Description: An AMI ID for the EC2 Instance
    Type: String
    Default: ami-0c94855ba95c71c99
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - m4.large
      - m4.xlarge
      - c4.large
      - c4.xlarge

Resources:
  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to host
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-sg

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
      - AssociatePublicIpAddress: True
        DeleteOnTermination: True
        DeviceIndex: 0
        GroupSet: 
          - !Ref Ec2SecurityGroup
        SubnetId: !Ref SubnetId
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install httpd -y
          service httpd start
          chkconfig httpd on
          cd /var/www/html
          echo "<html><h1>This is WebServer 01</h1></html>" > index.html
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ec2

Outputs:
  Ec2Id:
    Value: !Ref EC2Instance

  Ec2PublicId:
    Value: !GetAtt EC2Instance.PublicIp
