Description:
  This template deploys a VPC, with a pair of public and private subnets spread
  across two Availability Zones. It deploys an internet gateway, with a default
  route on the public subnets. It deploys a NAT gateway for the first private subnet,
  and default routes for it.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
  VpcId:
    Description: The VPC where the EC2 Instance will be launched
    Type: String
  SubnetId:
    Description: The Subnet where the EC2 Instance will be launched
    Type: String
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH Key to use
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - m4.large
      - m4.xlarge
      - c4.large
      - c4.xlarge
  SecurityGroup:
    Type: String
    Description: Security group for the EC2 Instance
  DBAddress:
    Type: String
    Description: Database endpoint
  DBName:
    Type: String
    Description: Database name
  DBUsername:
    Type: String
    Description: Username for MySQL database access
  DBPassword:
    Type: String
    Description: Password MySQL database access

Mappings:
  AWSInstanceType2Arch:
    t1.micro:
      Arch: PV64
    t2.micro:
      Arch: HVM64
    t2.small:
      Arch: HVM64
    t2.medium:
      Arch: HVM64
    m3.medium:
      Arch: PV64
    m3.large:
      Arch: PV64
    m3.xlarge:
      Arch: PV64
    m3.2xlarge:
      Arch: PV64
  AWSRegionArch2AMI:
    us-east-1:
      PV64: ami-7c807d14
      HVM64: ami-76817c1e
    us-west-2:
      PV64: ami-1b3b462b
      HVM64: ami-d13845e1
    us-west-1:
      PV64: ami-a8d3d4ed
      HVM64: ami-f0d3d4b5
    eu-west-1:
      PV64: ami-672ce210
      HVM64: ami-892fe1fe
    ap-southeast-1:
      PV64: ami-56b7eb04
      HVM64: ami-a6b6eaf4
    ap-northeast-1:
      PV64: ami-25dd9324
      HVM64: ami-29dc9228
    ap-southeast-2:
      PV64: ami-6bf99c51
      HVM64: ami-d9fe9be3
    sa-east-1:
      PV64: ami-c7e649da
      HVM64: ami-c9e649d4
    us-gov-west-1:
      PV64: ami-ab4a2d88
      HVM64: ami-a54a2d86
    cn-north-1:
      PV64: ami-cab82af3
      HVM64: ami-ccb82af5

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      ImageId: !FindInMap 
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref InstanceType
          - Arch
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
      - AssociatePublicIpAddress: True
        DeleteOnTermination: True
        DeviceIndex: 0
        GroupSet: 
          - !Ref SecurityGroup
        SubnetId: !Ref SubnetId
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install httpd php php-mysql -y
          cd /var/www/html
          wget https://wordpress.org/wordpress-5.1.1.tar.gz
          tar -xzf wordpress-5.1.1.tar.gz
          cp -r wordpress/* /var/www/html/
          rm -rf wordpress
          rm -rf wordpress-5.1.1.tar.gz
          chmod -R 755 wp-content
          chown -R apache:apache wp-content
          wget https://s3.amazonaws.com/bucketforwordpresslab-donotdelete/htaccess.txt
          mv htaccess.txt .htaccess
          chkconfig httpd on
          service httpd start
          cp wp-config-sample.php wp-config.php
          sed -i 's/database_name_here/${DBName}/g' wp-config.php
          sed -i 's/localhost/${DBAddress}/g' wp-config.php
          sed -i 's/username_here/${DBUsername}/g' wp-config.php
          sed -i 's/password_here/${DBPassword}/g' wp-config.php
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ec2

Outputs:
  Ec2Id:
    Value: !Ref EC2Instance

  Ec2PublicId:
    Value: !GetAtt EC2Instance.PublicIp
