AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH Key to use
  InstanceTypeECS:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - m4.large
      - m4.xlarge
      - c4.large
      - c4.xlarge
  EnvironmentName:
    Type: String
    Description: An environment name that is prefixed to resource names
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: >-
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.
  HostedZoneName:
    Type: String
    Description: The domain name that you want to create, update, or delete (example.com)
  HostedZoneId:
    Type: String
    Description: The ID of the hosted zone that you want to create records in Route53
  BucketUrl:
    Type: String
    Description: S3 bucket Url where the yaml files are uploaded
  DBName:
    Default: wordpress
    Description: DB name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
  DBUsername:
    NoEcho: 'true'
    Default: wordpressadmin
    Description: Username for MySQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Default: wpPassword123
    Description: Password MySQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${BucketUrl}/vpc.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
  
  RDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${BucketUrl}/rds.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        DBName: !Ref DBName
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
        VpcId: !GetAtt VPC.Outputs.VPC
        PrivateSubnet1: !GetAtt VPC.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPC.Outputs.PrivateSubnet2
  
  EC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${BucketUrl}/ec2.yaml
      Parameters:
        VpcId: !GetAtt VPC.Outputs.VPC
        SubnetId: !GetAtt VPC.Outputs.PublicSubnet1
        EnvironmentName: !Ref EnvironmentName
        KeyName: !Ref KeyName
        SecurityGroup: !GetAtt RDS.Outputs.EC2SecurityGroup
        DBAddress: !GetAtt RDS.Outputs.Endpoint
        DBName: !Ref DBName
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword

  Route53:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${BucketUrl}/route53.yaml
      Parameters:
        HostedZoneId: !Ref HostedZoneId
        Name: !Ref HostedZoneName
        ResourceRecords: !GetAtt EC2.Outputs.Ec2PublicId
